### ISSUE TITLE
make error: ‘AioCompletion’ is not a member of ‘zlog’

### ISSUE THREAD

**Issue by DeadFishw** [cruzdb/cruzdb#76]
I solved previous problems, but I ran into this new one. Could you specify which version of zlog are you building on? There was no slice.h in zlog 4.0 and later, and there is no eviction.h or staticstic.h in zlog 3.0 or earlier.

**Comment by dotnwat** [comment]
it looks like cruzdb master branch may work with zlog v0.3.0. but looking a bit closer, it seems that some of the newer branches like `new-ptree-2` may depend on newer versions of zlog because i don't see the same references to AioCompletion.
